package com.example.demo.ai;

import com.example.demo.ai.dto.AiChatRequest;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/ai")
public class AiChatController {

    private final ChatModel chatModel;

    public AiChatController(ChatModel chatModel) {
        this.chatModel = chatModel;
    }

    /**
     * General-purpose chat API using the llama3.2:3b model
     * @param request The request body containing the user’s prompt
     * @return The response text generated by the model
     */
    @PostMapping("/chat")
    public String chat(@RequestBody AiChatRequest request) {
        return chatModel.call(request.getPrompt());
    }

    /**
     * Chat API with additional metadata
     * @param request The request body containing the user’s prompt
     * @return complete ChatResponse object
     */
    @PostMapping("/chat/full")
    public ChatResponse chatFull(@RequestBody AiChatRequest request) {
        return chatModel.call(new Prompt(request.getPrompt()));
    }
}
