spring.application.name=demo

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
admin.token=dev-admin-token


ollama.base-url=${OLLAMA_BASE_URL:http://ollama:11434}
ollama.model=${OLLAMA_MODEL:llama3.2:3b}
ollama.timeout-ms=${OLLAMA_TIMEOUT_MS:60000}

ai.service.provider=${AI_SERVICE_PROVIDER:gemini}

anthropic.api-key=${ANTHROPIC_API_KEY}
anthropic.model=${ANTHROPIC_MODEL:claude-3-5-sonnet-20241022}
anthropic.base-url=https://api.anthropic.com/v1/messages

google.api-key=${GOOGLE_API_KEY}
google.base-url=https://generativelanguage.googleapis.com/v1beta/models/
google.model=${GOOGLE_MODEL:gemini-2.5-flash}

app.admin.email=hello@purposemediacbr.au

server.port=${PORT:8080}
